export const GET_CUSTOMER_PENDING = 'GET_CUSTOMER_PENDING';
export const GET_CUSTOMER_FULLFILLED = 'GET_CUSTOMER_FULLFILLED';
export const GET_CUSTOMER_REJECTED = 'GET_CUSTOMER_REJECTED';

export const GET_ROOM_PENDING = 'GET_ROOM_PENDING';
export const GET_ROOM_FULLFILLED = 'GET_ROOM_FULLFILLED';
export const GET_ROOM_REJECTED = 'GET_ROOM_REJECTED';

export const GET_USER_PENDING = 'GET_USER_PENDING';
export const GET_USER_FULLFILLED = 'GET_USER_FULLFILLED';
export const GET_USER_REJECTED = 'GET_USER_REJECTED';

export const GET_CHECKIN_PENDING = 'GET_CHECKIN_PENDING';
export const GET_CHECKIN_FULLFILLED = 'GET_CHECKIN_FULLFILLED';
export const GET_CHECKIN_REJECTED = 'GET_CHECKIN_REJECTED';
